# Exact reviewed runtime coordinate-to-SPDX mapping. Versions and hashes are locked separately.
com.typesafe:config=Apache-2.0
io.github.oshai:kotlin-logging-jvm=Apache-2.0
io.ktor:ktor-client-cio-jvm=Apache-2.0
io.ktor:ktor-client-core-jvm=Apache-2.0
io.ktor:ktor-events-jvm=Apache-2.0
io.ktor:ktor-http-cio-jvm=Apache-2.0
io.ktor:ktor-http-jvm=Apache-2.0
io.ktor:ktor-io-jvm=Apache-2.0
io.ktor:ktor-network-jvm=Apache-2.0
io.ktor:ktor-network-tls-jvm=Apache-2.0
io.ktor:ktor-serialization-jvm=Apache-2.0
io.ktor:ktor-serialization-kotlinx-json-jvm=Apache-2.0
io.ktor:ktor-serialization-kotlinx-jvm=Apache-2.0
io.ktor:ktor-server-cio-jvm=Apache-2.0
io.ktor:ktor-server-content-negotiation-jvm=Apache-2.0
io.ktor:ktor-server-core-jvm=Apache-2.0
io.ktor:ktor-server-cors-jvm=Apache-2.0
io.ktor:ktor-server-sse-jvm=Apache-2.0
io.ktor:ktor-server-websockets-jvm=Apache-2.0
io.ktor:ktor-sse-jvm=Apache-2.0
io.ktor:ktor-utils-jvm=Apache-2.0
io.ktor:ktor-websocket-serialization-jvm=Apache-2.0
io.ktor:ktor-websockets-jvm=Apache-2.0
io.modelcontextprotocol:kotlin-sdk-client-jvm=Apache-2.0
io.modelcontextprotocol:kotlin-sdk-core-jvm=Apache-2.0
io.modelcontextprotocol:kotlin-sdk-jvm=Apache-2.0
io.modelcontextprotocol:kotlin-sdk-server-jvm=Apache-2.0
org.fusesource.jansi:jansi=Apache-2.0
org.jetbrains.kotlin:kotlin-reflect=Apache-2.0
org.jetbrains.kotlin:kotlin-stdlib=Apache-2.0
org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm=Apache-2.0
org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm=Apache-2.0
org.jetbrains.kotlinx:kotlinx-coroutines-slf4j=Apache-2.0
org.jetbrains.kotlinx:kotlinx-io-bytestring-jvm=Apache-2.0
org.jetbrains.kotlinx:kotlinx-io-core-jvm=Apache-2.0
org.jetbrains.kotlinx:kotlinx-serialization-core-jvm=Apache-2.0
org.jetbrains.kotlinx:kotlinx-serialization-json-io-jvm=Apache-2.0
org.jetbrains.kotlinx:kotlinx-serialization-json-jvm=Apache-2.0
org.jetbrains:annotations=Apache-2.0
org.slf4j:slf4j-api=MIT
org.slf4j:slf4j-simple=MIT
